### PR TITLE
feat(api-docs): convert to openapi and add response type for deals

### PR DESCRIPTION
**Pull request by casaper**
Starting to fill issue #89 .

- Convert json to openapi doc using editor.swagger.io
- add response type for /ver1/bots/{bot_id}/show
- add response type for /ver1/deals

### CODE REVIEW

**Comment by casaper** [comment]
@marrychriss || @MoroZvlg 

BTW: I'm doing what 3commas actually should do, because the current swagger file is not only quite incomplete, but also qite wrong in some cases.

If it was OS, I wouldn't comment like that, but as a paying customer I see things a bit differently.

However:

Consider introducing [rswag](https://github.com/rswag/rswag) as your API testing tool. It not only brings better ways of testing API's, as its fine side product it also delivers a decent OpenAPI doc.

It looks like you guys use Rails, at least 3commas public API, but I'm not sure though.  
If not, I'm sure there is something similar to [rswag](https://github.com/rswag/rswag) out there, for what ever other tech 3commas might use.

**Comment by sadgb** [comment]
Hi @casaper thanks for your merge request. 
We will definitely approve it and make sure all the files stay actual by modifying our pipeline. 

We already have rswag ob board and use it for all new API methods added. We are trying to cover all the API but we need more time to make it fully covered. 

Once again, thanks for all your work, we appreciate it.

**Comment by casaper** [comment]
Hi @sadgb 

Great to hear.
So feel free to merge then, if it suits you.

Thx.

**Comment by EfremovEvgeniy** [comment]
Hi @casaper. Thank you for this merge request, we can merge but maybe sometimes this file will be overwritten by our docs generator.
We know about problems in our swagger docs and we have goals for this quarter to improve our docs. 
Once again, thank you

**Comment by casaper** [comment]
@EfremovEvgeniy

Since you use rswag, you could actually handle this quite easily. I did that in multiple projects with rswag, and I find it quite convenient, as a workflow:

spec/swagger_helper.rb
```ruby
require 'spec_helper'
require 'yaml'

schema_yaml = YAML.load_file(
  Rails.root.join('spec/swagger_schemas/swagger.yaml'),
  symbolize_names: true
)

RSpec.configure do |config|
  config.swagger_docs = {
    'v1/swagger.yaml' => {
      openapi: schema_yaml.fetch(:openapi, {}),
      info: schema_yaml.fetch(:info, {}).merge(
        version: "v#{Rails.application.whatever_gives_you_that_meta_data}"
      ),
      servers: schema_yaml[:servers],
      tags: schema_yaml.fetch(:tags, []),
      paths: {},
      components: {
        securitySchemes: schema_yaml[:components]&.fetch(:securitySchemes, {}),
        schemas:  schema_yaml.fetch(:components, { schemas: {} })[:schemas].except(
          # here you can skip keys (eg. yaml injects) you don't wan't in the generated version
          :example_key_store_has_to_be_first_in_schemas,
        )
      }
    }
  }
end
```

This allows you to have a base swagger.yml where you can create and shape by hand what ever you want, and rswag merges its output with it for you.


And then you can define the model keys as ref in your rswag specs -> and then we get generated return types.

```ruby
  path '/api/tasks' do
    get('index') do
      tags 'Tasks'
      consumes 'application/json'
      # without produces statement, rswag will not generate a return type!
      produces 'application/json'

      response(200, 'fetch all tasks') do
        schema type: :array, items: { '$ref' => '#/components/schemas/task' }

        run_test! do |response|
          body = parse_body(response)
          # whatever you expect
        end
      end
    end
  end
```

I have done this on multiple projects before, and have the workflow kind of in peto.

I don't know what the internals of the 3commas Rails app are, and how complex it is.
But depending on that, I'd do it within 3 days to 2 weeks.
I work for an Agency, so 3 commas could hire me for this if they like.

**Pull request merged**
